<<<<<<< HEAD
[pytest]
markers =
    positive: Тесты, которые проверяют корректное поведение функции
    negative: Тесты, которые проверяют некорректное поведение функции
=======
[pytest]
markers =
    positive: Тесты, которые проверяют корректное поведение функции
    negative: Тесты, которые проверяют некорректное поведение функции
>>>>>>> fcdbfdaaade2a912f92f8ed8a124a402b35bebc8
