[pytest]
filterwarnings =
    ignore::DeprecationWarning
markers =
    positive: Позитивные тесты
    negative: Негативные тесты
    smoke: Дымовые тесты
    regression: Регрессионные тесты
addopts =
    -v
    --strict-markers
    --tb=short
    --disable-warnings